### ISSUE TITLE
[test] 일반전 업데이트에 따른 테스트코드 작성

### ISSUE THREAD

**Issue by nheo9143** [42organization/42arcade.gg.server.dev#397]
> ### ISSUE
> * Type: `test`
> * Detail: 일반전 업데이트에 따른 테스트코드 작성 
> 
> ### TODO
> 1. [ ]  슬롯컨트롤러 노말 테스트 
> 2. [ ]  시즌 여러 개인 경우에 임의의 시즌 받아와서 데이터 잘 가져오는지 확인할 수 있도록 하는 코드(userhistoric 그래프, 게임 결과)
>

**Comment by wochae** [comment]
기한이 지난 이슈 종료
